<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>c4a0e73c-91d1-4f9e-b80e-3ba1714c1565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='pesan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;pesan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>466ec285-01e3-4c3f-b641-10cc60cce090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-user btn-block</value>
      <webElementGuid>adb8cdfe-0d86-4752-9900-8db94b215f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pesan</value>
      <webElementGuid>814bfa96-bf40-4b38-8669-9c7be6ef73a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>d65e3ee9-2981-47ce-ac7e-eeaed7e80055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-gradient-primary&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-xl-10 col-lg-12 col-md-9&quot;]/div[@class=&quot;card o-hidden border-0 shadow-lg my-5&quot;]/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;p-5&quot;]/form[1]/button[@class=&quot;btn btn-primary btn-user btn-block&quot;]</value>
      <webElementGuid>4a2311db-50ad-4714-9426-b9ac3cf1a10b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='pesan']</value>
      <webElementGuid>a9b11d2f-b8ce-4893-b9e0-b3d63e70702b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat Datang Admin'])[1]/following::button[1]</value>
      <webElementGuid>818f9358-8675-45f5-b7e9-2c9368699615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>c65ea945-096f-475c-84c0-4b236b38b0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e71438f1-760b-40ce-b855-1b07d49a0be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'pesan' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>e73dd2b2-4bd0-4ee7-9a3e-91d8256eccab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
